// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwplxdikxtnsoavmijpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cGx4ZGlreHRuc29hdm1panBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzQwMDAsImV4cCI6MjA2ODUxMDAwMH0.-p_Jb_fEHr1biucRvBPuWArgMF0libGNlk5aqppZCHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});